// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace movie_website_api.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20260704145503_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Actors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("ActorsVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdActors")
                        .HasColumnType("integer");

                    b.Property<int>("IdVideoItem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdActors");

                    b.HasIndex("IdVideoItem");

                    b.ToTable("ActorsVideo");
                });

            modelBuilder.Entity("AnimeStudios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnimeStudios");
                });

            modelBuilder.Entity("AnimeStudiosVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAnimeStudio")
                        .HasColumnType("integer");

                    b.Property<int>("IdVideoItem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdAnimeStudio");

                    b.HasIndex("IdVideoItem");

                    b.ToTable("AnimeStudiosVideo");
                });

            modelBuilder.Entity("BlockedCountries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCountry")
                        .HasColumnType("integer");

                    b.Property<int>("IdVideoItem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCountry");

                    b.HasIndex("IdVideoItem");

                    b.ToTable("BlockedCountries");
                });

            modelBuilder.Entity("BlockedSeasons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCountry")
                        .HasColumnType("integer");

                    b.Property<int>("IdVideoItem")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCountry");

                    b.HasIndex("IdVideoItem");

                    b.ToTable("BlockedSeasons");
                });

            modelBuilder.Entity("Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CountriesCreated", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCountry")
                        .HasColumnType("integer");

                    b.Property<int>("IdVideoItem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCountry");

                    b.HasIndex("IdVideoItem");

                    b.ToTable("VideoCountries");
                });

            modelBuilder.Entity("Directors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("DirectorsVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDirectors")
                        .HasColumnType("integer");

                    b.Property<int>("IdVideoItem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdDirectors");

                    b.HasIndex("IdVideoItem");

                    b.ToTable("DirectorsVideo");
                });

            modelBuilder.Entity("Genres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Producers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("ProducersVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProducers")
                        .HasColumnType("integer");

                    b.Property<int>("IdVideoItem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdProducers");

                    b.HasIndex("IdVideoItem");

                    b.ToTable("ProducersVideo");
                });

            modelBuilder.Entity("Screenshots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdVideoItem")
                        .HasColumnType("integer");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdVideoItem");

                    b.ToTable("Screenshots");
                });

            modelBuilder.Entity("Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VideoGenres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGenres")
                        .HasColumnType("integer");

                    b.Property<int>("IdVideoItem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdGenres");

                    b.HasIndex("IdVideoItem");

                    b.ToTable("VideoGenres");
                });

            modelBuilder.Entity("VideoItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiredAt")
                        .HasColumnType("text");

                    b.Property<string>("AllStatus")
                        .HasColumnType("text");

                    b.Property<string>("AnimeDescription")
                        .HasColumnType("text");

                    b.Property<string>("AnimeKind")
                        .HasColumnType("text");

                    b.Property<string>("AnimePosterUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int?>("EpisodesAired")
                        .HasColumnType("integer");

                    b.Property<int?>("EpisodesCount")
                        .HasColumnType("integer");

                    b.Property<int?>("EpisodesTotal")
                        .HasColumnType("integer");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text");

                    b.Property<double?>("ImdbRating")
                        .HasColumnType("double precision");

                    b.Property<int?>("ImdbVotes")
                        .HasColumnType("integer");

                    b.Property<string>("KinopoiskId")
                        .HasColumnType("text");

                    b.Property<double?>("KinopoiskRating")
                        .HasColumnType("double precision");

                    b.Property<int?>("KinopoiskVotes")
                        .HasColumnType("integer");

                    b.Property<int?>("LastEpisode")
                        .HasColumnType("integer");

                    b.Property<int?>("LastSeason")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MinimalAge")
                        .HasColumnType("integer");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text");

                    b.Property<string>("PremiereRu")
                        .HasColumnType("text");

                    b.Property<string>("PremiereWorld")
                        .HasColumnType("text");

                    b.Property<string>("RatingMpaa")
                        .HasColumnType("text");

                    b.Property<string>("ReleasedAt")
                        .HasColumnType("text");

                    b.Property<string>("ShikimoriId")
                        .HasColumnType("text");

                    b.Property<double?>("ShikimoriRating")
                        .HasColumnType("double precision");

                    b.Property<int?>("ShikimoriVotes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text");

                    b.Property<string>("TitleOrig")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorldartLink")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VideoItems");
                });

            modelBuilder.Entity("WatchListUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int>("IdVideoItem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("IdVideoItem");

                    b.ToTable("WatchListUsers");
                });

            modelBuilder.Entity("ActorsVideo", b =>
                {
                    b.HasOne("Actors", null)
                        .WithMany()
                        .HasForeignKey("IdActors")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoItems", null)
                        .WithMany()
                        .HasForeignKey("IdVideoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeStudiosVideo", b =>
                {
                    b.HasOne("AnimeStudios", null)
                        .WithMany()
                        .HasForeignKey("IdAnimeStudio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoItems", null)
                        .WithMany()
                        .HasForeignKey("IdVideoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlockedCountries", b =>
                {
                    b.HasOne("Countries", null)
                        .WithMany()
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoItems", null)
                        .WithMany()
                        .HasForeignKey("IdVideoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlockedSeasons", b =>
                {
                    b.HasOne("Countries", null)
                        .WithMany()
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoItems", null)
                        .WithMany()
                        .HasForeignKey("IdVideoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountriesCreated", b =>
                {
                    b.HasOne("Countries", null)
                        .WithMany()
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoItems", null)
                        .WithMany()
                        .HasForeignKey("IdVideoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectorsVideo", b =>
                {
                    b.HasOne("Directors", null)
                        .WithMany()
                        .HasForeignKey("IdDirectors")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoItems", null)
                        .WithMany()
                        .HasForeignKey("IdVideoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProducersVideo", b =>
                {
                    b.HasOne("Producers", null)
                        .WithMany()
                        .HasForeignKey("IdProducers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoItems", null)
                        .WithMany()
                        .HasForeignKey("IdVideoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Screenshots", b =>
                {
                    b.HasOne("VideoItems", null)
                        .WithMany()
                        .HasForeignKey("IdVideoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoGenres", b =>
                {
                    b.HasOne("Genres", null)
                        .WithMany()
                        .HasForeignKey("IdGenres")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoItems", null)
                        .WithMany()
                        .HasForeignKey("IdVideoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WatchListUsers", b =>
                {
                    b.HasOne("Users", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoItems", null)
                        .WithMany()
                        .HasForeignKey("IdVideoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
